// Code generated by go generate; DO NOT EDIT.
package commands

import (
	"github.com/brandonc/advent2022/solutions/day01"
	"github.com/brandonc/advent2022/solutions/solution"
)

var SolutionCommands = map[string]solution.SolutionFactory{
	"1": day01.Factory,
}
