// Code generated by go generate; DO NOT EDIT.
package commands

import (
	"github.com/brandonc/advent2022/solutions/day01"

	"github.com/mitchellh/cli"
)

var SolutionCommands = map[string]cli.CommandFactory{
	"1": day01.Command,
}
