package main

import (
	"os"

	"github.com/brandonc/advent2022/internal/commands"
	"github.com/brandonc/advent2022/internal/ui"

	"github.com/mitchellh/cli"
)

func main() {
	c := cli.NewCLI("advent2022", "12.25.2022")
	c.Args = os.Args[1:]
	c.Commands = commands.SolutionCommands // Generated by go generate

	exit, err := c.Run()
	ui.Die(err)
	os.Exit(exit)
}
